#!/usr/bin/env bash

echo "installing and updating PDEapprox dependencies"
# Move to project root
cd ..

parentname="$(basename "$(pwd)")"
if [ ! $parentname = "PDEapprox" ]; then
  echo "Attempted setup from wrong directory -- move to PDEapprox/bin!"
  exit 1
fi


# Dependencies contained in lib directory.
if [ ! -d 'lib' ]; then
  mkdir lib
fi
cd lib

if [ -d 'Winterval' ]; then 
  rm -r 'Winterval'
fi
wget 'https://github.com/Willmo3/Winterval/raw/refs/heads/main/release/winterval-v0.0.7.tar.gz'
tar -xzf 'winterval-v0.0.7.tar.gz' && rm 'winterval-v0.0.7.tar.gz'

if [ -d 'Caffeine' ]; then
  rm -r 'Caffeine'
fi
wget 'https://github.com/Willmo3/Caffeine/raw/refs/heads/main/release/caffeine-release.tar.gz'
tar -xzf 'caffeine-release.tar.gz' && rm 'caffeine-release.tar.gz'

if [ -d 'DualDomain' ]; then
  rm -r 'DualDomain'
fi
wget 'https://github.com/Willmo3/DualDomain/raw/refs/heads/main/release/dualdomain-v0.0.1.tar.gz'
tar -xzf 'dualdomain-v0.0.1.tar.gz' && rm 'dualdomain-v0.0.1.tar.gz'

# Cereal is required for wixed, waffine, and winterval
if [[ -d "cereal" ]]; then
  rm -r "cereal"
fi

wget "https://github.com/USCiLab/cereal/archive/v1.3.2.tar.gz" && tar -xf "v1.3.2.tar.gz" && mv "cereal-1.3.2/include/cereal/" "." && rm -r cereal-1.3.2 v1.3.2.tar.gz

# Download Matplotplusplus if not already present
if [ ! -d 'matplotplusplus' ]; then
  git clone "https://github.com/alandefreitas/matplotplusplus"
fi
# Note: we do not automatically update matplot++, as it's a larger project outside of our control.

